import { Head } from '@inertiajs/react';
import { FormEvent, useEffect, useMemo, useState } from 'react';

type Session={token:string;user:any;organizations:any[]};
type Step={key:string;type:string;config:any;retry:any};

async function api<T>(path:string,token:string,init:RequestInit={}):Promise<T>{
  const headers:any={Accept:'application/json',Authorization:`Bearer ${token}`,...(init.headers||{})};
  if(typeof init.body==='string')headers['Content-Type']='application/json';
  const response=await fetch(`/api${path}`,{...init,headers});
  const body=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(body.message||body.error?.code||`HTTP ${response.status}`);
  return body;
}
const uid=()=>crypto.randomUUID();

export default function Home(){
  const [session,setSession]=useState<Session|null>(()=>{try{return JSON.parse(localStorage.getItem('queueflow-session')||'null')}catch{return null}});
  if(!session)return <Auth onSession={setSession}/>;
  return <Workspace session={session} logout={()=>{localStorage.removeItem('queueflow-session');setSession(null)}}/>;
}

function Auth({onSession}:{onSession:(s:Session)=>void}){
  const [mode,setMode]=useState<'register'|'login'>('register'); const [error,setError]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const payload=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok){setError(b.message||'Authentication failed');return}const s={token:b.token,user:b.user,organizations:b.organizations||[b.organization]};localStorage.setItem('queueflow-session',JSON.stringify(s));onSession(s)}
  return <><Head title="QueueFlow"/><main className="auth-shell"><section><p className="eyebrow">DURABLE ASYNCHRONOUS SYSTEMS</p><h1>QueueFlow</h1><p className="lede">Design versioned workflows, trigger them asynchronously, and inspect every retry, dead letter, schedule and downstream call.</p></section><form className="card auth-card" onSubmit={submit}><h2>{mode==='register'?'Create workspace':'Sign in'}</h2>{error&&<div className="alert">{error}</div>}{mode==='register'&&<><input name="name" placeholder="Name" required/><input name="organization_name" placeholder="Organization" required/></>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" minLength={10} placeholder="Password (10+ characters)" required/><button>{mode==='register'?'Create workspace':'Sign in'}</button><button className="ghost" type="button" onClick={()=>setMode(mode==='register'?'login':'register')}>{mode==='register'?'Already registered? Sign in':'Need a workspace? Register'}</button></form></main></>;
}

function Workspace({session,logout}:{session:Session;logout:()=>void}){
  const org=session.organizations[0]; const [workflows,setWorkflows]=useState<any[]>([]); const [selected,setSelected]=useState<any>(); const [catalog,setCatalog]=useState<any>({}); const [metrics,setMetrics]=useState<any>(); const [secrets,setSecrets]=useState<any[]>([]); const [organizationState,setOrganizationState]=useState<any>(); const [error,setError]=useState('');
  async function refreshList(){const p:any=await api('/workflows?per_page=100',session.token);setWorkflows(p.data||p)}
  async function open(id:string){setSelected(await api(`/workflows/${id}`,session.token))}
  async function refreshOps(){const [m,se,o]=await Promise.all([api('/operations/metrics',session.token),api('/operations/secrets',session.token),api(`/operations/organizations/${org.id}`,session.token)]);setMetrics(m);setSecrets(se as any[]);setOrganizationState(o)}
  useEffect(()=>{Promise.all([refreshList(),api<any>('/operations/action-catalog',session.token).then(x=>setCatalog(x.actions)),refreshOps()]).catch(e=>setError(e.message))},[]);
  async function mutate(path:string,method='POST',body?:any){try{return await api<any>(path,session.token,{method,body:body===undefined?undefined:JSON.stringify(body)})}catch(e:any){setError(e.message);throw e}}
  return <><Head title="QueueFlow workspace"/><div className="app"><header><div><b>QueueFlow</b><span className="muted"> workflow control plane</span></div><div className="top-actions"><span>{session.user.name}</span><button className="ghost" onClick={logout}>Sign out</button></div></header>{error&&<div className="alert global" onClick={()=>setError('')}>{error}</div>}<div className="layout"><aside><CreateWorkflow organizationId={org.id} mutate={mutate} onCreated={async w=>{await refreshList();await open(w.id)}}/><h3>Workflows</h3>{workflows.map(w=><button className={`workflow-row ${selected?.id===w.id?'active':''}`} key={w.id} onClick={()=>open(w.id)}><b>{w.name}</b><small>{w.status} · v{w.current_version?.version_number||0} · {w.queue_priority}</small></button>)}<button className="ghost full" onClick={()=>{refreshList();refreshOps()}}>Refresh operations</button></aside><main>{selected?<WorkflowView workflow={selected} catalog={catalog} token={session.token} organizationId={org.id} organizationState={organizationState} mutate={mutate} refresh={async()=>{await open(selected.id);await refreshList();await refreshOps()}} metrics={metrics} secrets={secrets}/>:<Overview metrics={metrics} secrets={secrets} org={org} organizationState={organizationState} mutate={mutate} refresh={refreshOps}/>}</main></div></div></>;
}

function CreateWorkflow({organizationId,mutate,onCreated}:{organizationId:string;mutate:any;onCreated:(w:any)=>void}){const [name,setName]=useState('Order enrichment');async function submit(e:FormEvent){e.preventDefault();const w=await mutate('/workflows','POST',{organization_id:organizationId,name,max_concurrent_executions:5,queue_priority:'default'});onCreated(w)}return <form className="create" onSubmit={submit}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Workflow name"/><button>+</button></form>}

function Overview({metrics,secrets,org,organizationState,mutate,refresh}:{metrics:any;secrets:any[];org:any;organizationState:any;mutate:any;refresh:()=>void}){return <div><div className="hero"><div><p className="eyebrow">OPERATIONS</p><h1>Workflow engine</h1><p>Redis transports jobs. PostgreSQL owns workflow state, retry deadlines, usage counters and dead-letter recovery.</p></div></div><Metrics metrics={metrics}/><OrganizationSettings state={organizationState} mutate={mutate} refresh={refresh}/><SecretPanel secrets={secrets} org={org} mutate={mutate} refresh={refresh}/></div>}

function WorkflowView({workflow,catalog,token,organizationId,organizationState,mutate,refresh,metrics,secrets}:{workflow:any;catalog:any;token:string;organizationId:string;organizationState:any;mutate:any;refresh:()=>Promise<void>;metrics:any;secrets:any[]}){
  const source=workflow.current_version?.steps||[];
  const initial=source.length?source.map((s:any)=>({key:s.key,type:s.type,config:s.config_json,retry:s.retry_policy_json})):[defaultStep('transform',catalog)];
  const [steps,setSteps]=useState<Step[]>(initial); const [context,setContext]=useState('{"customer":{"id":"cus_123"},"notification_email":"ops@example.com"}'); const [execution,setExecution]=useState<any>(); const [deadLetters,setDeadLetters]=useState<any[]>([]);
  useEffect(()=>{setSteps(source.length?source.map((s:any)=>({key:s.key,type:s.type,config:s.config_json,retry:s.retry_policy_json})):[defaultStep('transform',catalog)])},[workflow.id,workflow.current_version_id]);
  async function publish(){await mutate(`/workflows/${workflow.id}/publish`,'POST',{steps});await refresh()}
  async function trigger(){let c={};try{c=JSON.parse(context)}catch{return alert('Context must be valid JSON')}const e=await api<any>(`/workflows/${workflow.id}/trigger`,token,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':uid()},body:JSON.stringify({context:c})});await watch(e.id);await refresh()}
  async function watch(id:string){const e:any=await api(`/executions/${id}`,token);setExecution(e);if(!['succeeded','failed','cancelled'].includes(e.status))setTimeout(()=>watch(id),1000)}
  async function loadDead(){const p:any=await api(`/workflows/${workflow.id}/dead-letters?unresolved=0`,token);setDeadLetters(p.data||p)}
  return <div><div className="hero"><div><p className="eyebrow">{workflow.status.toUpperCase()} · {workflow.queue_priority.toUpperCase()} QUEUE</p><h1>{workflow.name}</h1><p>{workflow.max_concurrent_executions} workflow executions may run concurrently. Published versions are immutable.</p></div><div className="actions"><button onClick={publish}>Publish new version</button><button className="secondary" onClick={trigger} disabled={!workflow.current_version_id}>Trigger run</button></div></div><div className="tabs-grid"><section className="card span2"><div className="row"><h3>Workflow definition</h3><span>next v{(workflow.current_version?.version_number||0)+1}</span></div><div className="steps">{steps.map((step,i)=><StepEditor key={`${step.key}-${i}`} step={step} index={i} catalog={catalog} update={s=>setSteps(v=>v.map((x,n)=>n===i?s:x))} remove={()=>setSteps(v=>v.filter((_,n)=>n!==i))}/>)}</div><button className="ghost" onClick={()=>setSteps(v=>[...v,defaultStep(Object.keys(catalog)[0]||'transform',catalog)])}>+ Add step</button></section><section className="card"><h3>Manual trigger context</h3><textarea rows={10} value={context} onChange={e=>setContext(e.target.value)}/><small>Each manual run sends a new Idempotency-Key. Reuse the same key through the API to prove trigger deduplication.</small></section></div><div className="tabs-grid"><TriggerSettings workflow={workflow} mutate={mutate} refresh={refresh}/><SecretPanel secrets={secrets} org={{id:organizationId}} mutate={mutate} refresh={refresh}/></div><VersionHistory versions={workflow.versions||[]}/><OrganizationSettings state={organizationState} mutate={mutate} refresh={refresh}/><ExecutionHistory workflow={workflow} token={token} watch={watch} mutate={mutate} refresh={refresh}/>{execution&&<ExecutionDetail data={execution} mutate={mutate} watch={watch}/>}<section className="card"><div className="row"><h3>Dead letters</h3><button className="ghost" onClick={loadDead}>Load history</button></div>{deadLetters.length===0?<p className="muted">No loaded dead letters.</p>:deadLetters.map(d=><div className="log-row" key={d.id}><code>{d.failure_code}</code><span>{String(d.step_execution_id).slice(0,8)}</span><small>{d.resolved_at?'resolved':'unresolved'}</small></div>)}</section><Metrics metrics={metrics}/></div>;
}

function defaultStep(type:string,catalog:any):Step{return {key:`step_${Math.random().toString(36).slice(2,7)}`,type,config:structuredClone(catalog[type]?.config||{}),retry:{max_attempts:3,mode:'exponential',base_delay_seconds:5,max_delay_seconds:300,jitter:true}}}
function StepEditor({step,index,catalog,update,remove}:{step:Step;index:number;catalog:any;update:(s:Step)=>void;remove:()=>void}){const [config,setConfig]=useState(JSON.stringify(step.config,null,2));const [retry,setRetry]=useState(JSON.stringify(step.retry,null,2));useEffect(()=>setConfig(JSON.stringify(step.config,null,2)),[step.type]);function commit(field:'config'|'retry',value:string){try{update({...step,[field]:JSON.parse(value)})}catch{/* retain editor until valid */}}return <article className="step"><div className="step-no">{index+1}</div><div className="step-body"><div className="row"><input value={step.key} onChange={e=>update({...step,key:e.target.value})}/><select value={step.type} onChange={e=>{const type=e.target.value;const s={...step,type,config:structuredClone(catalog[type]?.config||{})};update(s);setConfig(JSON.stringify(s.config,null,2))}}>{Object.entries(catalog).map(([type,v]:any)=><option value={type} key={type}>{v.label}</option>)}</select><button className="danger" onClick={remove}>Remove</button></div><p>{catalog[step.type]?.description}</p><div className="editor-grid"><label>Config<textarea rows={8} value={config} onChange={e=>setConfig(e.target.value)} onBlur={()=>commit('config',config)}/></label><label>Retry policy<textarea rows={8} value={retry} onChange={e=>setRetry(e.target.value)} onBlur={()=>commit('retry',retry)}/></label></div></div></article>}

function TriggerSettings({workflow,mutate,refresh}:{workflow:any;mutate:any;refresh:()=>Promise<void>}){const [secret,setSecret]=useState('');const [cron,setCron]=useState('*/5 * * * *');async function webhook(){const x=await mutate(`/workflows/${workflow.id}/webhook`);setSecret(x.secret);await refresh()}async function schedule(e:FormEvent){e.preventDefault();await mutate(`/workflows/${workflow.id}/schedules`,'POST',{cron,timezone:'UTC'});await refresh()}return <section className="card"><h3>Triggers</h3><div className="row"><span>Webhook</span><button className="secondary" onClick={webhook}>{workflow.webhook_endpoint?'Rotate secret':'Create webhook'}</button></div>{workflow.webhook_endpoint&&<code className="block">{workflow.webhook_endpoint.url}</code>}{secret&&<div className="secret-reveal"><b>Copy once</b><code>{secret}</code></div>}<form className="schedule" onSubmit={schedule}><input value={cron} onChange={e=>setCron(e.target.value)}/><button>Add UTC schedule</button></form>{(workflow.schedules||[]).map((s:any)=><div className="log-row" key={s.id}><code>{s.cron_expression}</code><span>{s.next_run_at}</span><button className="danger" onClick={async()=>{await mutate(`/workflows/${workflow.id}/schedules/${s.id}`,'DELETE');await refresh()}}>Delete</button></div>)}</section>}

function SecretPanel({secrets,org,mutate,refresh}:{secrets:any[];org:any;mutate:any;refresh:()=>void}){const [name,setName]=useState('API_TOKEN');const [value,setValue]=useState('');async function save(e:FormEvent){e.preventDefault();if(!value)return;await mutate('/operations/secrets','POST',{organization_id:org.id,name,value});setValue('');refresh()}return <section className="card"><h3>Connector secrets</h3><form className="schedule" onSubmit={save}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Secret name"/><input type="password" value={value} onChange={e=>setValue(e.target.value)} placeholder="Secret value"/><button>Save</button></form>{secrets.filter(s=>s.organization_id===org.id).map(s=><div className="log-row" key={s.id}><code>{s.name}</code><small>updated {new Date(s.updated_at).toLocaleString()}</small><button className="danger" onClick={async()=>{await mutate(`/operations/secrets/${s.id}`,'DELETE');refresh()}}>Delete</button></div>)}</section>}

function ExecutionHistory({workflow,token,watch,mutate,refresh}:{workflow:any;token:string;watch:(id:string)=>void;mutate:any;refresh:()=>Promise<void>}){const rows=workflow.recent_executions||[];return <section className="card"><h3>Recent executions</h3>{rows.length===0?<p className="muted">Publish and trigger the workflow to create an execution.</p>:rows.map((e:any)=><div className="execution-row" key={e.id} role="button" tabIndex={0} onClick={()=>watch(e.id)} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();watch(e.id)}}}><span className={`status ${e.status}`}>{e.status}</span><code>{String(e.id).slice(0,8)}</code><span>{e.trigger_type}</span><small>{new Date(e.created_at).toLocaleString()}</small>{['failed'].includes(e.status)&&<button className="mini" onClick={async ev=>{ev.stopPropagation();await mutate(`/executions/${e.id}/retry`);watch(e.id);await refresh()}}>Retry</button>}{['pending','running'].includes(e.status)&&<button className="mini danger" onClick={async ev=>{ev.stopPropagation();await mutate(`/executions/${e.id}/cancel`);watch(e.id);await refresh()}}>Cancel</button>}</div>)}</section>}

function VersionHistory({versions}:{versions:any[]}){return <section className="card"><h3>Published-version history</h3>{[...versions].sort((a,b)=>b.version_number-a.version_number).map(v=><details key={v.id}><summary>v{v.version_number} · {v.status||'published'} · {new Date(v.created_at).toLocaleString()}</summary><pre>{JSON.stringify((v.steps||[]).map((s:any)=>({position:s.position,key:s.key,type:s.type,config:s.config_json,retry:s.retry_policy_json})),null,2)}</pre></details>)}</section>}
function OrganizationSettings({state,mutate,refresh}:{state:any;mutate:any;refresh:()=>void}){const org=state?.organization;const usage=state?.usage;const [concurrency,setConcurrency]=useState('');const [limit,setLimit]=useState('');useEffect(()=>{if(org){setConcurrency(String(org.max_concurrent_executions??20));setLimit(String(org.monthly_execution_limit??0))}},[org?.id,org?.updated_at]);if(!org)return null;async function save(e:FormEvent){e.preventDefault();await mutate(`/operations/organizations/${org.id}`,'PATCH',{max_concurrent_executions:Number(concurrency),monthly_execution_limit:Number(limit)});await refresh()}return <section className="card"><div className="row"><h3>Organization usage & limits</h3><span>{usage?.execution_count||0} executions this month</span></div><form className="schedule" onSubmit={save}><label>Concurrent executions<input type="number" min="1" value={concurrency} onChange={e=>setConcurrency(e.target.value)}/></label><label>Monthly execution limit (0 = unlimited)<input type="number" min="0" value={limit} onChange={e=>setLimit(e.target.value)}/></label><button>Save limits</button></form></section>}
function ExecutionDetail({data,mutate,watch}:{data:any;mutate:any;watch:(id:string)=>void}){return <section className="card"><div className="row"><h3>Execution {String(data.id).slice(0,8)}</h3><span className={`status ${data.status}`}>{data.status}</span></div><details><summary>Execution context</summary><pre>{JSON.stringify(data.context_json,null,2)}</pre></details><div className="timeline">{(data.steps||[]).map((s:any)=><article key={s.id}><div><b>{s.workflow_step?.key}</b><small>{s.workflow_step?.type}</small></div><span className={`status ${s.status}`}>{s.status}</span><span>attempts {s.attempt_count}</span>{s.started_at&&s.completed_at&&<small>{new Date(s.completed_at).getTime()-new Date(s.started_at).getTime()} ms</small>}{s.retry_at&&<small>retry {new Date(s.retry_at).toLocaleTimeString()}</small>}{s.error_message&&<code className="error-code">{s.error_class}: {s.error_message}</code>}<details><summary>Input / output preview</summary><pre>{JSON.stringify({input:s.input_json,output:s.output_json},null,2)}</pre></details>{(s.attempts||[]).map((a:any)=><small key={a.id}>#{a.attempt_number} {a.status} · {a.worker_identifier}{a.started_at&&a.finished_at?` · ${new Date(a.finished_at).getTime()-new Date(a.started_at).getTime()} ms`:''}</small>)}</article>)}</div>{data.status==='failed'&&<button onClick={async()=>{await mutate(`/executions/${data.id}/retry`);watch(data.id)}}>Retry terminal execution</button>}</section>}

function Metrics({metrics}:{metrics:any}){if(!metrics)return null;return <section className="card"><h3>24-hour operations</h3><div className="metrics"><Metric label="Executions" value={metrics.executions}/><Metric label="Executions/min" value={metrics.executions_per_minute}/><Metric label="Success" value={`${Math.round((metrics.success_rate||0)*100)}%`}/><Metric label="Step failures" value={`${Math.round((metrics.step_failure_rate||0)*100)}%`}/><Metric label="Retries" value={metrics.retry_attempts}/><Metric label="p95 workflow" value={metrics.duration_ms?.p95?`${metrics.duration_ms.p95} ms`:'—'}/><Metric label="p95 downstream" value={metrics.downstream_latency_ms?.p95?`${metrics.downstream_latency_ms.p95} ms`:'—'}/></div><pre>{JSON.stringify({queue_depth:metrics.queue_depth,oldest_queued_job_age_seconds:metrics.oldest_queued_job_age_seconds},null,2)}</pre></section>}
function Metric({label,value}:{label:string;value:any}){return <div><small>{label}</small><b>{value??'—'}</b></div>}
