<?php
namespace App\Domain\Workflow\Handlers;
use App\Domain\Workflow\{ActionFailure,ActionHandler,ActionResult,SsrfGuard,WebhookSignature};use App\Services\{ConnectorSecretResolver,DownstreamThrottle,TemplateRenderer};use Illuminate\Support\Facades\Http;use InvalidArgumentException;
final class OutboundWebhookAction implements ActionHandler
{
 public function __construct(private SsrfGuard $guard,private DownstreamThrottle $throttle,private ConnectorSecretResolver $secrets,private TemplateRenderer $templates,private WebhookSignature $signatures){}
 public function type():string{return 'outbound_webhook';}public function validateConfig(array $c):void{if(empty($c['url']))throw new InvalidArgumentException('url is required');$this->guard->assertPublicHttpUrl((string)$c['url']);}
 public function execute(array $c,array $context,string $idempotencyKey):ActionResult{$this->validateConfig($c);$url=(string)$this->templates->render($c['url'],$context);$this->guard->assertPublicHttpUrl($url);$org=(string)($context['__organization_id']??'');$this->throttle->consume($org,(string)parse_url($url,PHP_URL_HOST),(int)($c['requests_per_minute']??60));$payload=$this->templates->render($c['payload']??$context,$context);$json=json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$timestamp=time();$headers=['Content-Type'=>'application/json','Idempotency-Key'=>$idempotencyKey,'X-QueueFlow-Timestamp'=>(string)$timestamp];if(!empty($c['signing_secret_name'])){$secret=$this->secrets->get($org,(string)$c['signing_secret_name']);$headers['X-QueueFlow-Signature']=$this->signatures->sign($json,$secret,$timestamp);}try{$response=Http::withHeaders($headers)->timeout((int)($c['timeout_seconds']??15))->withBody($json,'application/json')->post($url);}catch(\Throwable $e){throw new ActionFailure($e->getMessage(),'transient');}if($response->status()===429)throw new ActionFailure('Webhook rate limited','rate_limit',(int)($response->header('Retry-After')?:5));if($response->serverError())throw new ActionFailure('Webhook server error','http_5xx');if(!$response->successful())throw new ActionFailure('Webhook rejected with HTTP '.$response->status(),'validation');return new ActionResult(['webhook'=>['status'=>$response->status()]]);}
}
