<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
Schema::create('workflows',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('organization_id')->index();$t->string('name');$t->string('slug');$t->string('status')->default('draft')->index();$t->uuid('current_version_id')->nullable();$t->timestamps();$t->unique(['organization_id','slug']);$t->foreign('organization_id')->references('id')->on('organizations')->cascadeOnDelete();});
Schema::create('workflow_versions',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('workflow_id')->index();$t->unsignedInteger('version_number');$t->jsonb('definition_json');$t->timestampTz('published_at')->nullable();$t->timestamps();$t->unique(['workflow_id','version_number']);$t->foreign('workflow_id')->references('id')->on('workflows')->cascadeOnDelete();});
Schema::create('workflow_steps',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('workflow_version_id')->index();$t->string('key');$t->string('type');$t->unsignedInteger('position');$t->jsonb('config_json');$t->jsonb('retry_policy_json');$t->timestamps();$t->unique(['workflow_version_id','key']);$t->unique(['workflow_version_id','position']);$t->foreign('workflow_version_id')->references('id')->on('workflow_versions')->cascadeOnDelete();});
Schema::table('workflows',fn(Blueprint $t)=>$t->foreign('current_version_id')->references('id')->on('workflow_versions')->nullOnDelete());
Schema::create('workflow_executions',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('organization_id')->index();$t->uuid('workflow_version_id')->index();$t->string('trigger_type');$t->string('idempotency_key');$t->string('status')->index();$t->jsonb('context_json');$t->timestampTz('started_at')->nullable();$t->timestampTz('completed_at')->nullable();$t->string('failure_code')->nullable();$t->timestamps();$t->unique(['organization_id','workflow_version_id','idempotency_key']);$t->foreign('organization_id')->references('id')->on('organizations')->cascadeOnDelete();$t->foreign('workflow_version_id')->references('id')->on('workflow_versions')->restrictOnDelete();});
Schema::create('step_executions',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('workflow_execution_id')->index();$t->uuid('workflow_step_id')->index();$t->string('status')->index();$t->unsignedInteger('attempt_count')->default(0);$t->jsonb('input_json')->nullable();$t->jsonb('output_json')->nullable();$t->timestampTz('started_at')->nullable();$t->timestampTz('completed_at')->nullable();$t->string('error_class')->nullable();$t->text('error_message')->nullable();$t->timestamps();$t->unique(['workflow_execution_id','workflow_step_id']);$t->foreign('workflow_execution_id')->references('id')->on('workflow_executions')->cascadeOnDelete();$t->foreign('workflow_step_id')->references('id')->on('workflow_steps')->restrictOnDelete();});
Schema::create('execution_attempts',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('step_execution_id')->index();$t->unsignedInteger('attempt_number');$t->string('worker_identifier')->nullable();$t->timestampTz('started_at');$t->timestampTz('finished_at')->nullable();$t->string('status');$t->jsonb('error_metadata_json')->nullable();$t->timestamps();$t->unique(['step_execution_id','attempt_number']);$t->foreign('step_execution_id')->references('id')->on('step_executions')->cascadeOnDelete();});
Schema::create('webhook_endpoints',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('workflow_id')->unique();$t->text('secret_encrypted');$t->boolean('enabled')->default(true);$t->timestampTz('last_received_at')->nullable();$t->timestamps();$t->foreign('workflow_id')->references('id')->on('workflows')->cascadeOnDelete();});
Schema::create('scheduled_triggers',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('workflow_id')->index();$t->string('cron_expression');$t->string('timezone')->default('UTC');$t->timestampTz('next_run_at')->index();$t->timestamps();$t->foreign('workflow_id')->references('id')->on('workflows')->cascadeOnDelete();});
}public function down():void{Schema::dropIfExists('scheduled_triggers');Schema::dropIfExists('webhook_endpoints');Schema::dropIfExists('execution_attempts');Schema::dropIfExists('step_executions');Schema::dropIfExists('workflow_executions');Schema::table('workflows',fn(Blueprint $t)=>$t->dropForeign(['current_version_id']));Schema::dropIfExists('workflow_steps');Schema::dropIfExists('workflow_versions');Schema::dropIfExists('workflows');}};
