<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::table('organizations',function(Blueprint $t){$t->string('plan')->default('developer');$t->string('status')->default('active');$t->unsignedInteger('max_concurrent_executions')->default(10);$t->unsignedBigInteger('monthly_execution_limit')->default(0);});
 Schema::table('workflows',function(Blueprint $t){$t->unsignedInteger('max_concurrent_executions')->default(5);$t->string('queue_priority')->default('default');});
 Schema::table('step_executions',function(Blueprint $t){$t->string('logical_key')->nullable()->index();$t->timestampTz('retry_at')->nullable();$t->timestampTz('dead_lettered_at')->nullable();});
 Schema::create('connector_secrets',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('organization_id')->index();$t->string('name');$t->text('secret_encrypted');$t->timestamps();$t->unique(['organization_id','name']);$t->foreign('organization_id')->references('id')->on('organizations')->cascadeOnDelete();});
 Schema::create('dead_letters',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('workflow_execution_id')->index();$t->uuid('step_execution_id')->index();$t->string('failure_code');$t->jsonb('error_metadata_json')->nullable();$t->timestampTz('created_at');$t->timestampTz('resolved_at')->nullable();$t->foreign('workflow_execution_id')->references('id')->on('workflow_executions')->cascadeOnDelete();$t->foreign('step_execution_id')->references('id')->on('step_executions')->cascadeOnDelete();});
 Schema::create('organization_execution_usage',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('organization_id')->index();$t->date('period_start');$t->unsignedBigInteger('execution_count')->default(0);$t->timestamps();$t->unique(['organization_id','period_start']);$t->foreign('organization_id')->references('id')->on('organizations')->cascadeOnDelete();});
 }public function down():void{Schema::dropIfExists('organization_execution_usage');Schema::dropIfExists('dead_letters');Schema::dropIfExists('connector_secrets');Schema::table('step_executions',fn(Blueprint $t)=>$t->dropColumn(['logical_key','retry_at','dead_lettered_at']));Schema::table('workflows',fn(Blueprint $t)=>$t->dropColumn(['max_concurrent_executions','queue_priority']));Schema::table('organizations',fn(Blueprint $t)=>$t->dropColumn(['plan','status','max_concurrent_executions','monthly_execution_limit']));}};
