<?php
namespace App\Http\Controllers;
use App\Domain\Workflow\{StepExecutionStatus,WorkflowExecutionStatus};use App\Jobs\ExecuteWorkflowStep;use App\Models\{ConnectorSecret,DeadLetter,ScheduledTrigger,WebhookEndpoint,Workflow,WorkflowExecution};use App\Services\WorkflowQueue;use Cron\CronExpression;use Illuminate\Http\{JsonResponse,Request};use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
final class WorkflowOperationsController
{
 public function execution(Request $r,WorkflowExecution $execution):JsonResponse{$this->auth($r,$execution->organization_id);$execution->load('steps.workflowStep','steps.attempts','version.workflow');$secrets=ConnectorSecret::where('organization_id',$execution->organization_id)->pluck('secret_encrypted')->filter()->values()->all();$data=$execution->toArray();$data=$this->redact($data,$secrets);return response()->json($data);}
 public function retry(Request $r,WorkflowExecution $execution,WorkflowQueue $queues):JsonResponse{$this->auth($r,$execution->organization_id);abort_unless($execution->status===WorkflowExecutionStatus::Failed,409);DB::transaction(function()use($execution){$e=WorkflowExecution::lockForUpdate()->findOrFail($execution->id);$failed=$e->steps()->with('workflowStep')->where('status',StepExecutionStatus::Failed->value)->orderByRaw('(select position from workflow_steps where workflow_steps.id=step_executions.workflow_step_id)')->firstOrFail();$position=$failed->workflowStep->position;$failed->update(['status'=>StepExecutionStatus::Pending,'retry_at'=>null,'dead_lettered_at'=>null,'completed_at'=>null,'error_class'=>null,'error_message'=>null]);$e->steps()->where('status',StepExecutionStatus::Skipped->value)->whereHas('workflowStep',fn($q)=>$q->where('position','>',$position))->update(['status'=>StepExecutionStatus::Pending,'completed_at'=>null]);DeadLetter::where('step_execution_id',$failed->id)->whereNull('resolved_at')->update(['resolved_at'=>now()]);$e->update(['status'=>WorkflowExecutionStatus::Running,'completed_at'=>null,'failure_code'=>null]);},3);$fresh=$execution->fresh()->load('version.workflow');ExecuteWorkflowStep::dispatch($execution->id)->onQueue($queues->name($fresh->version->workflow));return response()->json(['status'=>'retry_queued'],202);}
 public function cancel(Request $r,WorkflowExecution $execution):JsonResponse{$this->auth($r,$execution->organization_id);abort_unless(in_array($execution->status,[WorkflowExecutionStatus::Pending,WorkflowExecutionStatus::Running],true),409);DB::transaction(function()use($execution){$e=WorkflowExecution::lockForUpdate()->findOrFail($execution->id);$e->steps()->whereIn('status',[StepExecutionStatus::Pending->value,StepExecutionStatus::RetryWait->value])->update(['status'=>StepExecutionStatus::Skipped,'completed_at'=>now()]);$e->update(['status'=>WorkflowExecutionStatus::Cancelled,'completed_at'=>now()]);},3);return response()->json(['status'=>'cancelled']);}
 public function webhook(Request $r,Workflow $workflow):JsonResponse{$this->auth($r,$workflow->organization_id);$secret='qfw_'.Str::random(48);$endpoint=WebhookEndpoint::updateOrCreate(['workflow_id'=>$workflow->id],['secret_encrypted'=>$secret,'enabled'=>true]);return response()->json(['endpoint_id'=>$endpoint->id,'secret'=>$secret,'url'=>url('/api/hooks/'.$endpoint->id)],201);}
 public function schedule(Request $r,Workflow $workflow):JsonResponse{$this->auth($r,$workflow->organization_id);$d=$r->validate(['cron'=>'required|string|max:100','timezone'=>'required|timezone']);abort_unless(CronExpression::isValidExpression($d['cron']),422,'Invalid cron expression');$cron=new CronExpression($d['cron']);$next=$cron->getNextRunDate(now()->toDateTime(),0,false,$d['timezone']);$s=ScheduledTrigger::create(['workflow_id'=>$workflow->id,'cron_expression'=>$d['cron'],'timezone'=>$d['timezone'],'next_run_at'=>$next]);return response()->json($s,201);}
 public function deleteSchedule(Request $r,Workflow $workflow,ScheduledTrigger $schedule):JsonResponse{$this->auth($r,$workflow->organization_id);abort_unless($schedule->workflow_id===$workflow->id,404);$schedule->delete();return response()->json(['deleted'=>true]);}
 private function redact(mixed $value,array $secrets):mixed{if(is_array($value))return array_map(fn($v)=>$this->redact($v,$secrets),$value);if(!is_string($value))return $value;foreach($secrets as $secret)if($secret!=='')$value=str_replace($secret,'[REDACTED]',$value);return $value;}
 private function auth(Request $r,string $org):void{abort_unless($r->user()->organizations()->whereKey($org)->exists(),403);}
}
