<?php
namespace App\Jobs;
use App\Domain\Workflow\{ActionFailure,ActionRegistry,RetryPolicy,StepExecutionStatus,WorkflowExecutionStatus};use App\Models\{DeadLetter,ExecutionAttempt,StepExecution,WorkflowExecution};use App\Services\WorkflowQueue;use Illuminate\Bus\Queueable;use Illuminate\Contracts\Queue\ShouldQueue;use Illuminate\Foundation\Bus\Dispatchable;use Illuminate\Queue\{InteractsWithQueue,SerializesModels};use Illuminate\Support\Facades\{Cache,DB,Log};use Throwable;
final class ExecuteWorkflowStep implements ShouldQueue
{
 use Dispatchable,InteractsWithQueue,Queueable,SerializesModels;public int $tries=1;public int $timeout=120;public function __construct(public string $executionId){}
 public function handle(ActionRegistry $registry,RetryPolicy $retryPolicy,WorkflowQueue $queues):void{$lock=Cache::lock("qf:execution:{$this->executionId}:claim",130);if(!$lock->get()){self::dispatch($this->executionId)->delay(2)->onQueue($this->queue??'workflows');return;}try{$claim=DB::transaction(function(){$execution=WorkflowExecution::with('version.workflow')->lockForUpdate()->findOrFail($this->executionId);if(in_array($execution->status,[WorkflowExecutionStatus::Succeeded,WorkflowExecutionStatus::Failed,WorkflowExecutionStatus::Cancelled],true))return null;if($execution->status===WorkflowExecutionStatus::Pending)$execution->update(['status'=>WorkflowExecutionStatus::Running,'started_at'=>now()]);$step=$execution->steps()->with('workflowStep')->where('status',StepExecutionStatus::Pending->value)->orderByRaw('(select position from workflow_steps where workflow_steps.id=step_executions.workflow_step_id)')->lockForUpdate()->first();if(!$step){$this->finalizeIfSettled($execution);return null;}$step->update(['status'=>StepExecutionStatus::Running,'attempt_count'=>$step->attempt_count+1,'started_at'=>now(),'input_json'=>$execution->context_json]);$attempt=ExecutionAttempt::create(['step_execution_id'=>$step->id,'attempt_number'=>$step->attempt_count,'worker_identifier'=>(gethostname()?:'worker').':'.getmypid(),'started_at'=>now(),'status'=>'running']);return[$execution->fresh(),$step->fresh(),$attempt];},3);if(!$claim)return;[$execution,$step,$attempt]=$claim;$workflow=$execution->version()->with('workflow')->firstOrFail()->workflow;$handler=$registry->get($step->workflowStep->type);$logicalKey=$step->logical_key?:"{$execution->id}:{$step->workflowStep->key}";$actionStarted=microtime(true);try{$result=$handler->execute($step->workflowStep->config_json,$execution->context_json??[],$logicalKey);DB::transaction(function()use($execution,$step,$attempt,$result){$locked=StepExecution::with('workflowStep')->lockForUpdate()->findOrFail($step->id);if($locked->status!==StepExecutionStatus::Running)return;$locked->update(['status'=>StepExecutionStatus::Succeeded,'output_json'=>$result->output,'completed_at'=>now(),'error_class'=>null,'error_message'=>null]);$attempt->update(['status'=>'succeeded','finished_at'=>now()]);$fresh=WorkflowExecution::lockForUpdate()->findOrFail($execution->id);$fresh->update(['context_json'=>array_replace($fresh->context_json??[],$result->output)]);if($result->skipNext){$next=$fresh->steps()->where('status',StepExecutionStatus::Pending->value)->whereHas('workflowStep',fn($q)=>$q->where('position','>',$locked->workflowStep->position))->with('workflowStep')->get()->sortBy(fn($s)=>$s->workflowStep->position)->first();$next?->update(['status'=>StepExecutionStatus::Skipped,'completed_at'=>now()]);}},3);Log::info('queueflow.step.succeeded',$this->logContext($execution,$step)+['duration_ms'=>(int)((microtime(true)-$actionStarted)*1000)]);self::dispatch($execution->id)->delay($result->delaySeconds??0)->onQueue($queues->name($workflow));}
 catch(Throwable $e){[$classification,$retryAfter]=$this->classify($e);$decision=$retryPolicy->decide($step->attempt_count,$classification,$step->workflowStep->retry_policy_json??[],$retryAfter);DB::transaction(function()use($execution,$step,$attempt,$e,$classification,$decision){$locked=StepExecution::with('workflowStep')->lockForUpdate()->findOrFail($step->id);if($locked->status!==StepExecutionStatus::Running)return;$message=mb_substr($e->getMessage(),0,1000);$attempt->update(['status'=>'failed','finished_at'=>now(),'error_metadata_json'=>['class'=>get_class($e),'message'=>$message,'classification'=>$classification,'retry_after_seconds'=>$decision->delaySeconds]]);if($decision->retry){$locked->update(['status'=>StepExecutionStatus::RetryWait,'retry_at'=>now()->addSeconds($decision->delaySeconds),'error_class'=>$classification,'error_message'=>$message]);return;}$locked->update(['status'=>StepExecutionStatus::Failed,'completed_at'=>now(),'dead_lettered_at'=>now(),'error_class'=>$classification,'error_message'=>$message]);$position=$locked->workflowStep->position;StepExecution::query()->where('workflow_execution_id',$execution->id)->where('status',StepExecutionStatus::Pending->value)->whereHas('workflowStep',fn($q)=>$q->where('position','>',$position))->update(['status'=>StepExecutionStatus::Skipped,'completed_at'=>now()]);DeadLetter::create(['workflow_execution_id'=>$execution->id,'step_execution_id'=>$locked->id,'failure_code'=>$classification,'error_metadata_json'=>['exception'=>get_class($e),'message'=>$message,'attempts'=>$locked->attempt_count],'created_at'=>now()]);WorkflowExecution::whereKey($execution->id)->update(['status'=>WorkflowExecutionStatus::Failed,'failure_code'=>$classification,'completed_at'=>now()]);},3);Log::warning('queueflow.step.failed',$this->logContext($execution,$step)+['classification'=>$classification,'retry'=>$decision->retry,'retry_delay_seconds'=>$decision->delaySeconds]);if($decision->retry)ReleaseRetryStep::dispatch($step->id)->delay($decision->delaySeconds)->onQueue($queues->name($workflow));}}
 finally{$lock->release();}}
 private function finalizeIfSettled(WorkflowExecution $execution):void{if($execution->steps()->whereIn('status',[StepExecutionStatus::RetryWait->value,StepExecutionStatus::Running->value,StepExecutionStatus::Pending->value])->exists())return;$failed=$execution->steps()->where('status',StepExecutionStatus::Failed->value)->exists();$execution->update(['status'=>$failed?WorkflowExecutionStatus::Failed:WorkflowExecutionStatus::Succeeded,'completed_at'=>now()]);}
 private function classify(Throwable $e):array{if($e instanceof ActionFailure)return[$e->classification,$e->retryAfterSeconds];$message=strtolower($e->getMessage());if(str_contains($message,'429')||str_contains($message,'rate limit'))return['rate_limit',null];if(str_contains($message,'401')||str_contains($message,'403'))return['authentication',null];if($e instanceof \InvalidArgumentException)return['configuration',null];return['transient',null];}
 private function logContext(WorkflowExecution $e,StepExecution $s):array{return['organization_id'=>$e->organization_id,'workflow_id'=>$e->context_json['__workflow_id']??null,'execution_id'=>$e->id,'step_execution_id'=>$s->id,'job_id'=>$this->job?->getJobId()];}
}
